### PR TITLE
Added Template and Route for Preview Image Generator

### PR DESCRIPTION
**Pull request by rpalakkal**
This could be used to replace the stock preview image currently used for all email links with a more customized image. The template is different than the instagram one, and more closely aligns with the current image preview, but adds information about state and city/county.

### CODE REVIEW

**Comment by shortcircuit3** [comment]
Love this. I've been wanting to do this.

Right now I'm hosting it on heroku and the API craps out from time to time because its on a free instance. My only fear with using this for the meta previews is how we can have the api scal and serve all the requests coming in.

What do you think? What hosting/infra would we need to handle the load?

**Comment by shortcircuit3** [comment]
Also please share generated image here

**Comment by rpalakkal** [comment]
Image

Here is a sample generated image. Totally understand the concerns about api scalability, especially if it's running on a Heroku free instance right now. Ideally, there would be a constantly running server, but probably for the high volume we get, it would be quite expensive to do that. 

I'm thinking we could it using a serverless architecture - I tried doing this through Vercel/AWS, and it works pretty well. Here's another sample link: https://defund12.vercel.app/api/preview?state=CA&city=Walla+Walla . I don't think load would be a problem with serverless, though I'm not too familiar. 

If using the API on demand for meta preview doesn't work, I have two other ideas, which may require a bit more work:
1. When generating the static site from Gatsby, we could also add the generation of meta previews to the build process. This would, no doubt, increase build times by a good amount, but then we would not have to worry at all about hosting the API.
2. We could set up a simple storage bucket (using AWS, GCP/Firebase - many high-performance, free options) to cache meta previews when they are generated. Then when a request is made to the API, first it checks if the thumbnail already exists. If it does, it just pulls and sends it from the storage bucket. If not, it generates it, adds to the storage bucket, and then sends it. This would require some more infrastructure, setup, and work, so not really too sure if it's worth it - just thought I'd put out the idea.

**Comment by shortcircuit3** [comment]
oh wow, vercel is much quicker/better than the heroku api. What's the cost of running the api there?

We'd need to discuss some form of payment for the infra. @bingbongle would have a better idea of whats possibe.

Also the S3 bucket idea is much better than generating these fresh everytime. And using some form of redis cache to pull pre-generated images.

My thoughts/decision matrix

- All in all this is great and the solutions suggested are great additions
- Going forward with this depends on how much time we'd need to invest and what the ongoing infra costs would be. Does it make sense rolling this out? Is it a good use of time and resources

To decide, we need to figure out 
- Itemized infra costs
- Who's paying the bill
- Is the benefit worth the cost

**Comment by rpalakkal** [comment]
vercel is actually free(unless you want some corporate/professional dev features)! it runs on AWS lambda functions, which gives it great performance. I don't think there would be any infra costs for the api, and I'm assuming a storage bucket with <1gb of photos should be free or very cheap. 

I've been playing around with including it in the gatsby build, and generating the images while generating the pages actually works really well. On my old macbook, generating all images for the site took a little under 2 minutes. Also, for people doing dev on their machines, I made it only generate an image if the file doesn't already exist, so after the initial build, the build time would be about the same as it is right now. I'm leaning towards this option since it doesn't require any additional infra (which would inevitably require some maintenance). Additionally, the performance for users would be optimal, since just like it is now, the image would just be loaded from defund12.org/images/...

I can open up a PR on the main repo with the code for generating images on build and maybe we could take it from there?

**Comment by shortcircuit3** [comment]
Dope. Theres also a simple react frontend here: https://defund12-image-api.herokuapp.com/

Can you get this hosted too? The non technical team uses it to generate insta images.

If we move everything over, i'm happy rolling with this given its all free.

**Pull request closed without merging**
